kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:7135424f6836ee166d1199e88cfb95ee88efaf91
  - linuxkit/runc:efcece75889aec4e2de0d95ba27ccc46438522b3
  - linuxkit/containerd:ce79d5d4ab9c46f4763735c6e4ab5c51c3feb5d8
  - linuxkit/ca-certificates:d4cc1b82c73d272e94d0e71ea375fe56b0c0626a
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:c5f4b4895844b993dce4e8b35fd8263a6b557807
services:
  - name: getty
    image: linuxkit/getty:bae9e3d4861173bacf78f14a4fe44997a430d13b
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:814d1a3a76e84eae01a94575c038fd22652f94e3
  - name: dhcpcd
    image: linuxkit/dhcpcd:330839488cd122db3c44738e265c035c9729a963
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
