kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:bf45651001f871323d70b746330e8c2a94f767e6
  - linuxkit/runc:ab0b50b622b8e34031b6bb8b18497100a558a11d
  - linuxkit/containerd:c85f857bb3ed72b91509df20d1b9b3e430160074
onboot:
  - name: sysctl
    image: linuxkit/sysctl:118703ca489a425ee588096a3fa002ce29bf0b4c
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: linuxkit/sshd:b894b88581c8a8742d5c1323783116c85957e7d8
  - name: getty
    image: linuxkit/getty:76554bbf9f667205c78ce589c55100376fa16e28
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
