kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:30e04e810c9d3d54ab1eb6c2d9407a09d4f2709a
  - linuxkit/runc:8b5af3365fc7d015db4e44113d93c7b1f8e2d2ab
  - linuxkit/containerd:8072efcee7c1d77a6b41093ae610062552e354fb
onboot:
  - name: sysctl
    image: linuxkit/sysctl:112fe3d480ccb6cd115d9d6c446f9d833f6b8e68
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: linuxkit/sshd:db2374b91531e9fa1ebf63aeccb3963bee2aa771
  - name: getty
    image: linuxkit/getty:70237b8ac2006b0177026520e7720fc574339298
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
