kernel:
  image: "linuxkitprojects/kernel-memorizer:4.10_dbg"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:7135424f6836ee166d1199e88cfb95ee88efaf91
  - linuxkit/runc:efcece75889aec4e2de0d95ba27ccc46438522b3
  - linuxkit/containerd:ce79d5d4ab9c46f4763735c6e4ab5c51c3feb5d8
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:330839488cd122db3c44738e265c035c9729a963
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:bae9e3d4861173bacf78f14a4fe44997a430d13b
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
