kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:30e04e810c9d3d54ab1eb6c2d9407a09d4f2709a
  - linuxkit/runc:8b5af3365fc7d015db4e44113d93c7b1f8e2d2ab
  - linuxkit/containerd:8072efcee7c1d77a6b41093ae610062552e354fb
  - linuxkit/ca-certificates:422d213bd5fff6177be9219a1e0dfc39d9d75342
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:112fe3d480ccb6cd115d9d6c446f9d833f6b8e68
  - name: dhcpcd
    image: linuxkit/dhcpcd:f46134c05f9665d8865a9fbebd5be0995057af28
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:57e031c56e7911083e531963993e0accf7f2b33e
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
