kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:c9a1adb982eb4074c01a34ce43860b6df24c252d
  - linuxkit/runc:bcd6268ea2d45dc7c6b43ca82d00dd01e7105f17
  - linuxkit/containerd:d33b20080a2f88e833680dc8563b5a03a13a297e
  - linuxkit/ca-certificates:e1688f69167c991bf5be1be809fd68685a4a4a9a
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0c5861d22fac133d5bf679e763a1df14ad927de2
  - name: dhcpcd
    image: linuxkit/dhcpcd:c1f461bd40fabb1f3bb77348ab52abad8393bdb3
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:9812bcbb096ae21650a32a1517a5903efd8ff40b
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
