apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: open-vm-tools
  name: open-vm-tools
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: open-vm-tools
  template:
    metadata:
      labels:
        app: open-vm-tools
    spec:
      hostNetwork: true
      hostPID: true
      priorityClassName: system-cluster-critical
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - image: linuxkit/open-vm-tools:f3fa2fa157e65744feeda793089df8d069c8b962
        name: open-vm-tools
        resources:
          requests:
            memory: "5Mi"
            cpu: "100m"
          limits:
            memory: "25Mi"
            cpu: "500m"
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
