kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:bf45651001f871323d70b746330e8c2a94f767e6
  - linuxkit/runc:ab0b50b622b8e34031b6bb8b18497100a558a11d
  - linuxkit/containerd:c85f857bb3ed72b91509df20d1b9b3e430160074
  - linuxkit/ca-certificates:9179129925943ab3e8d4a92e986d8c87193925bc
onboot:
  - name: sysctl
    image: linuxkit/sysctl:118703ca489a425ee588096a3fa002ce29bf0b4c
  - name: dhcpcd
    image: linuxkit/dhcpcd:f67a935a3768da88a5d8252188e71b65f0feadf7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:3f1b4b04f51c06a751cadccc682868aad44be1aa
  - name: format
    image: linuxkit/format:db495c67312fe0ee4d94518e316a76f49ce01c40
  - name: mount
    image: linuxkit/mount:4711fa808be15ad41129c11a24bbb87efed0beec
    command: ["/usr/bin/mountie", "/var/lib/docker"]

services:
  - name: getty
    image: linuxkit/getty:76554bbf9f667205c78ce589c55100376fa16e28
    env:
      - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:e83de73632097eab9f96593f287dc032c3da5e75
  - name: ntpd
    image: linuxkit/openntpd:38d2ce3c14c3ad971eafced40ee486b7a0f892bf

  - name: docker
    image: docker:20.10.6-dind
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /var/run:/var/run
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: cadvisor
    image: linuxkit/cadvisor:63c1dee58823ed29472f231eddd2faf8c6d435e2
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true, "hosts": ["unix:///var/run/docker.sock"]}'
    mode: "0644"
