kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:bf45651001f871323d70b746330e8c2a94f767e6
  - linuxkit/runc:ab0b50b622b8e34031b6bb8b18497100a558a11d
  - linuxkit/containerd:c85f857bb3ed72b91509df20d1b9b3e430160074
  - linuxkit/ca-certificates:9179129925943ab3e8d4a92e986d8c87193925bc
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:f67a935a3768da88a5d8252188e71b65f0feadf7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:76554bbf9f667205c78ce589c55100376fa16e28
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.5
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.9
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - KAPACITOR_URL=http://127.0.0.1:9092
