# Simple example of using an external logging service
kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:30e04e810c9d3d54ab1eb6c2d9407a09d4f2709a
  - linuxkit/runc:8b5af3365fc7d015db4e44113d93c7b1f8e2d2ab
  - linuxkit/containerd:8072efcee7c1d77a6b41093ae610062552e354fb
  - linuxkit/ca-certificates:422d213bd5fff6177be9219a1e0dfc39d9d75342
  - linuxkit/memlogd:b15eb4d07ee3a50708a310ba62eb9330b61182e2
onboot:
  - name: sysctl
    image: linuxkit/sysctl:112fe3d480ccb6cd115d9d6c446f9d833f6b8e68
  - name: dhcpcd
    image: linuxkit/dhcpcd:f46134c05f9665d8865a9fbebd5be0995057af28
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
# Inside the getty type `/proc/1/root/usr/bin/logread -F` to follow the log
  - name: getty
    image: linuxkit/getty:70237b8ac2006b0177026520e7720fc574339298
    env:
     - INSECURE=true
# A service which generates log messages for testing
  - name: write-to-the-logs
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while /bin/true; do echo hello $(date); sleep 1; done" ]
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:678308bdb6421f32ff79b61ac2d95e9c8e41e080
  - name: kmsg
    image: linuxkit/kmsg:2cee55de43a863c9f1a28fe5a00e4730564e1826
