kernel:
  image: linuxkit/kernel:6.6.13-rt
  cmdline: "console=tty0"
init:
  - linuxkit/init:c9a1adb982eb4074c01a34ce43860b6df24c252d
  - linuxkit/runc:bcd6268ea2d45dc7c6b43ca82d00dd01e7105f17
  - linuxkit/containerd:d33b20080a2f88e833680dc8563b5a03a13a297e
  - linuxkit/ca-certificates:e1688f69167c991bf5be1be809fd68685a4a4a9a
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0c5861d22fac133d5bf679e763a1df14ad927de2
services:
  - name: getty
    image: linuxkit/getty:42bfdda2fef25c9fd84a58bb88de1496a7cafcda
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:9812bcbb096ae21650a32a1517a5903efd8ff40b
  - name: dhcpcd
    image: linuxkit/dhcpcd:c1f461bd40fabb1f3bb77348ab52abad8393bdb3
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:ba6486a746d1cbdca8f38cd5b03c79fcea14bf55
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
