kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:30e04e810c9d3d54ab1eb6c2d9407a09d4f2709a
  - linuxkit/runc:8b5af3365fc7d015db4e44113d93c7b1f8e2d2ab
  - linuxkit/containerd:8072efcee7c1d77a6b41093ae610062552e354fb
  - linuxkit/ca-certificates:422d213bd5fff6177be9219a1e0dfc39d9d75342
onboot:
  - name: sysctl
    image: linuxkit/sysctl:112fe3d480ccb6cd115d9d6c446f9d833f6b8e68
services:
  - name: rngd
    image: linuxkit/rngd:57e031c56e7911083e531963993e0accf7f2b33e
  - name: dhcpcd
    image: linuxkit/dhcpcd:f46134c05f9665d8865a9fbebd5be0995057af28
  - name: sshd
    image: linuxkit/sshd:db2374b91531e9fa1ebf63aeccb3963bee2aa771
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
