kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:c9a1adb982eb4074c01a34ce43860b6df24c252d
  - linuxkit/runc:bcd6268ea2d45dc7c6b43ca82d00dd01e7105f17
  - linuxkit/containerd:d33b20080a2f88e833680dc8563b5a03a13a297e
onboot:
  - name: ip
    image: linuxkit/ip:612bd1ef619e4409807713feaf6c436a0211b8b4
    binds:
     - /etc/ip:/etc/ip
    command: ["ip", "-b", "/etc/ip/eth0.conf"]
services:
  - name: getty
    image: linuxkit/getty:42bfdda2fef25c9fd84a58bb88de1496a7cafcda
    env:
     - INSECURE=true
files:     
  - path: etc/ip/eth0.conf
    contents: |
      address add 10.10.1.225/24 dev eth0
      link set eth0 up
      route add default via 10.10.1.100 dev eth0
  - path: etc/resolv.conf
    contents: |
#      domain test.local
      nameserver 10.10.1.101
      nameserver 10.10.1.100     
