kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:7135424f6836ee166d1199e88cfb95ee88efaf91
  - linuxkit/runc:efcece75889aec4e2de0d95ba27ccc46438522b3
  - linuxkit/containerd:ce79d5d4ab9c46f4763735c6e4ab5c51c3feb5d8
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:330839488cd122db3c44738e265c035c9729a963
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount-vpnkit
    image: alpine:3.13
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
services:
  - name: sshd
    image: linuxkit/sshd:964253f208c6ca5dffdb62ce10f5819206027e24
    binds.add:
      - /root/.ssh:/root/.ssh
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:930e9d3756e4b701595bf72c80e56d70abff70a1
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]

files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
