kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:c9a1adb982eb4074c01a34ce43860b6df24c252d
  - linuxkit/runc:bcd6268ea2d45dc7c6b43ca82d00dd01e7105f17
  - linuxkit/containerd:d33b20080a2f88e833680dc8563b5a03a13a297e
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:c1f461bd40fabb1f3bb77348ab52abad8393bdb3
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount-vpnkit
    image: alpine:3.13
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
services:
  - name: sshd
    image: linuxkit/sshd:e5622bc1d8f757c91bb35f0d5e708889f337bdaf
    binds.add:
      - /root/.ssh:/root/.ssh
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:135927339bb2d6416bca3a2eefe1c8239bc4d817
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]

files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
