kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:c9a1adb982eb4074c01a34ce43860b6df24c252d
  - linuxkit/runc:bcd6268ea2d45dc7c6b43ca82d00dd01e7105f17
  - linuxkit/containerd:d33b20080a2f88e833680dc8563b5a03a13a297e
  - linuxkit/ca-certificates:e1688f69167c991bf5be1be809fd68685a4a4a9a
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0c5861d22fac133d5bf679e763a1df14ad927de2
  - name: sysfs
    image: linuxkit/sysfs:b77e6229c5b673421fc4fa938d02907278e895c3
  - name: dhcpcd
    image: linuxkit/dhcpcd:c1f461bd40fabb1f3bb77348ab52abad8393bdb3
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:1214ae707090285cec2102e696c62892e3d8d0aa
  - name: mount
    image: linuxkit/mount:7cffeb3a4a77af09397479fe8e21c0dfce438cd0
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:42bfdda2fef25c9fd84a58bb88de1496a7cafcda
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:9812bcbb096ae21650a32a1517a5903efd8ff40b
  - name: ntpd
    image: linuxkit/openntpd:58cc4dc0fcc1f4cabbe586277cc2949337da5e31
  - name: docker
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/run:/var/run
     - /etc/html:/var/html
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: compose
    image: linuxkitprojects/compose:111f9f32a933c9e7acbf3ccfc13fedbdfce8224f
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: var/lib/docker
    directory: true
  - path: etc/html/a/index.html
    source: html-a.html
  - path: etc/html/b/index.html
    source: html-b.html
  - path: etc/compose/docker-compose.yml
    source: docker-compose.yml
  - path: etc/compose/images/nginx:alpine.tar
    source: image-cache/nginx:alpine.tar
  - path: etc/compose/images/traefik.tar
    source: image-cache/traefik.tar
trust:
  org:
    - linuxkit
    - library
